### PR TITLE
Use @@chef_config_dir in chef 12+ like knife.

### LINKED ISSUE #25: Undefined method "locate_config_file" with chef 12 / chefdk 0.3.5
Upon upgrading from chefdk 0.2.0 to 0.3.5, knife block broke down emitting:

Exception: NoMethodError: undefined method `locate_config_file' for Chef::Knife:Class

The 0.3.5 version of:
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-11.6.2/lib/chef/knife.rb

does indeed have changes to locate_config_file from the comparable 0.2.0 which no doubt has implicatations for knife-block's own get_config_file / locate_config_file logic.  

There were a few intervening releases from 0.2.0 to 0.3.5 that I did not use.

Chefdk 0.3.5 has no problems with the knife-block gem removed and knife-block works fine when installed with 0.2.0.

To workaround the problem, I donwgraded to 0.2.0 for now.

### PR DESCRIPTION
**Pull request by tbunnyman**
Fixes #25
Tests pass OS X 10.10 chefdk 0.4.0

### CODE REVIEW

**Comment by tbunnyman** [comment]
The ruby 2.2 tests are completely broken with an error on trying to load the test framework, however the 2.0 and 2.1 tests passed, hooray!!

I will try to patch the 2.2 tests but AFAIK chef isn't working with 2.2, omnibus uses 2.1 still

**Comment by tbunnyman** [comment]
Ok I woke up and tested this and it din't work after being compiled. However I went and grabbed the other PR for this and tried it and it works... so I'm closing this. Sorry for submitting before compiling and trying
